# Generated by Django 4.2.2 on 2023-06-24 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_create_date_alter_post_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 24, 7, 36, 53, 584954, tzinfo=datetime.timezone.utc)),
        ),
    ]
