# Generated by Django 4.2.2 on 2023-07-10 04:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_comment_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 10, 4, 3, 52, 325830, tzinfo=datetime.timezone.utc)),
        ),
    ]
